#!/usr/bin/env python3
"""Apply researched guide content to the HTML shells generated by _generate.py."""
from pathlib import Path
import html as html_lib
import re

BASE = Path(__file__).resolve().parent
SOURCE_DIR = BASE / ".content" / "guides"
UPDATED = "09/09/2026"

META_RE = re.compile(r"<!--\s*(title|description):\s*(.*?)\s*-->", re.I)
H2_RE = re.compile(r'<h2\s+id="([^"]+)"[^>]*>(.*?)</h2>', re.I | re.S)


def clean_text(value: str) -> str:
    value = re.sub(r"<[^>]+>", " ", value)
    return re.sub(r"\s+", " ", html_lib.unescape(value)).strip()


def load_source(path: Path):
    raw = path.read_text(encoding="utf-8")
    meta = {k.lower(): v for k, v in META_RE.findall(raw)}
    body = META_RE.sub("", raw).strip()
    if "title" not in meta or "description" not in meta:
        raise ValueError(f"metadata title/description missing in {path}")
    return meta, body


def replace_once(pattern, repl, text, label):
    out, count = re.subn(pattern, repl, text, count=1, flags=re.I | re.S)
    if count != 1:
        raise ValueError(f"{label}: expected one replacement, got {count}")
    return out


def build_toc(body: str) -> str:
    links = []
    for anchor, title in H2_RE.findall(body):
        if "source" in clean_text(title).lower():
            continue
        links.append(f'<a href="#{anchor}">{clean_text(title)}</a>')
    return "".join(links)


def apply(slug: str, source: Path):
    target = BASE / "guides" / slug / "index.html"
    if not target.exists():
        raise FileNotFoundError(target)
    meta, body = load_source(source)
    page = target.read_text(encoding="utf-8")

    page = replace_once(r"<title>.*?</title>", f"<title>{meta['title']}</title>", page, f"{slug} title")
    safe_desc = html_lib.escape(meta["description"], quote=True)
    page = replace_once(r'<meta\s+name="description"\s+content="[^"]*">', f'<meta name="description" content="{safe_desc}">', page, f"{slug} meta")
    page = replace_once(r'(<section class="page-hero">.*?<h1[^>]*>).*?(</h1>)', rf"\g<1>{meta['title']}\2", page, f"{slug} h1")
    page = replace_once(r'(<section class="page-hero">.*?<p class="lead">).*?(</p>)', rf"\g<1>{meta['description']}\2", page, f"{slug} lead")
    page = re.sub(r"Vérifié\s*:\s*MM/AAAA", f"Vérifié : {UPDATED}", page, flags=re.I)
    page = re.sub(r"Vérifié\s*:\s*\d{2}/\d{2}/\d{4}", f"Vérifié : {UPDATED}", page, flags=re.I)

    article = f'<article class="content-main">\n<!-- GUIDE_CONTENT_START -->\n{body}\n<!-- GUIDE_CONTENT_END -->\n</article>'
    page = replace_once(r'<article class="content-main">.*?</article>', article, page, f"{slug} article")

    toc = build_toc(body)
    page = replace_once(r'(<nav class="toc-list">).*?(</nav>)', rf"\g<1>{toc}\2", page, f"{slug} toc")

    if 'name="robots" content="noindex, follow"' not in page:
        raise ValueError(f"{slug}: noindex, follow must be preserved")
    if "<!-- Contenu à rédiger -->" in page:
        raise ValueError(f"{slug}: placeholder remains")
    target.write_text(page, encoding="utf-8")
    print(f"generated {slug}")


def main():
    sources = sorted(SOURCE_DIR.glob("*.html"))
    if not sources:
        raise SystemExit("no guide content sources found")
    for source in sources:
        apply(source.stem, source)
    print(f"PASS: generated {len(sources)} guides")


if __name__ == "__main__":
    main()
